export const HERO_TABS = [
  {
    id: 'authors-submit',
    type: 'cta',
    titleKey: 'home.hero.becomeAuthor',
    headlineKey: 'home.hero.publishHeadline',
    descriptionKey: 'home.hero.publishDescription',
    primaryCta: { href: '/authors/submit', labelKey: 'home.hero.publishCta' },
    secondaryCta: { href: '/authors', labelKey: 'home.hero.learnMoreCta' },
    accent: 'from-violet-600 via-fuchsia-600 to-orange-500',
    icon: 'PenSquare',
  },
  {
    id: 'authors-guide',
    type: 'cta',
    titleKey: 'home.hero.prepareManuscript',
    headlineKey: 'home.hero.guideHeadline',
    descriptionKey: 'home.hero.guideDescription',
    primaryCta: { href: '/authors/guide', labelKey: 'home.hero.prepareCta' },
    secondaryCta: { href: '/authors/webinars', labelKey: 'home.hero.eventsCta' },
    accent: 'from-amber-500 via-rose-500 to-purple-600',
    icon: 'LibraryBig',
  },
  {
    id: 'bestsellers-1',
    type: 'books',
    titleKey: 'home.hero.bestsellersOne',
    chunkIndex: 0,
  },
  {
    id: 'bestsellers-2',
    type: 'books',
    titleKey: 'home.hero.bestsellersTwo',
    chunkIndex: 1,
  },
  {
    id: 'bestsellers-3',
    type: 'books',
    titleKey: 'home.hero.bestsellersThree',
    chunkIndex: 2,
  },
];
